### ISSUE TITLE
在死亡不掉落的情况下，让需要的玩家自行选择开启

### ISSUE THREAD

**Issue by xiaoluofa** [YufiriaMazenta/CustomKeepInventory#1]

**Comment by YufiriaMazenta** [comment]
死亡不掉落时无法获取将掉落的物品，所以并不是很好的方式，不过我做了个默认的值，当玩家还未设置死亡不掉时，默认使用此值https://github.com/YufiriaMazenta/CustomKeepInventory/releases/tag/1.0.1
